services:
  redpanda:
    image: redpandadata/redpanda:v24.2.5
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --overprovisioned
      - --kernel-page-cache
      - --reserve-memory
      - "0M"
      - --check=false
      - --node-id
      - "0"
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://127.0.0.1:9092,OUTSIDE://127.0.0.1:19092
    ports:
      - "19092:19092"  # Kafka external
      - "9092:9092"    # Kafka internal
      - "9644:9644"    # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redpanda-console:
    image: redpandadata/console:v3.2.2
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - CONSOLE_CONFIG_BACKEND=redpanda
      - CONSOLE_REDPANDA_ADMIN_API=http://127.0.0.1:9644
      - CONSOLE_LISTEN_ADDRESS=0.0.0.0:8080

volumes:
  redpanda_data:
